import "server-only";
import fixture from "../../../fixtures/demo-observations.json";
import type { ActionResult, Observations, TestCode } from "@/contracts/domain";
import { getEvaluationWorkspace, saveObservationsService, evaluateTestService } from "@/server/workflow/evaluation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { normalizeSpecification } from "@/domain/oiml/schemas/specifications";
const now=()=>new Date().toISOString();
function raw(code:TestCode):Observations{
  const at=now();
  if(code==="WEIGHING_INITIAL")return{type:code,zeroReferences:[{rowKey:"demo-zero-before",zeroReferenceId:"z-before",loadG:"0",indicationG:fixture.weighing.beforeAndAfterZeroReadings[0].indicationG,additionalLoadG:fixture.weighing.beforeAndAfterZeroReadings[0].additionalLoadG,changeoverConfirmed:false,observedAt:at},{rowKey:"demo-zero-after",zeroReferenceId:"z-after",loadG:"0",indicationG:fixture.weighing.beforeAndAfterZeroReadings[1].indicationG,additionalLoadG:fixture.weighing.beforeAndAfterZeroReadings[1].additionalLoadG,changeoverConfirmed:false,observedAt:at}],rows:fixture.weighing.rows.map((r,i)=>({rowKey:`demo-weigh-${i+1}`,loadG:r.loadG,indicationG:r.indicationG,additionalLoadG:r.additionalLoadG,changeoverConfirmed:false,observedAt:at,direction:r.direction as "INCREASING"|"DECREASING",zeroReferenceId:r.direction==="INCREASING"?"z-before":"z-after"}))};
  if(code==="ECCENTRICITY_WEIGHTS"){const zeroReferences=fixture.eccentricity.rows.map(r=>({rowKey:`demo-ecc-zero-${r.segment}`,zeroReferenceId:`ez-${r.segment}`,loadG:r.zeroReference.loadG,indicationG:r.zeroReference.indicationG,additionalLoadG:r.zeroReference.additionalLoadG,changeoverConfirmed:false,observedAt:at}));return{type:code,sketchAttachmentId:"NOT_RECORDED",displayPositionDescription:"NOT RECORDED — tester must upload and describe the actual sketch",zeroReferences,rows:fixture.eccentricity.rows.map(r=>({rowKey:`demo-ecc-${r.segment}`,segment:r.segment as 1|2|3|4,loadG:r.loadG,indicationG:r.indicationG,additionalLoadG:r.additionalLoadG,changeoverConfirmed:false,observedAt:at,zeroReferenceId:`ez-${r.segment}`}))};}
  return{type:code,series:fixture.repeatability.map((series,index)=>({designation:index===0?"ABOUT_HALF_MAX":"CLOSE_TO_MAX",loadG:series.loadG,loadSelectionReason:"Raw fictional DEMO-30 fixture value; tester review required",rows:series.rows.map((r,i)=>({rowKey:`demo-repeat-${index+1}-${i+1}`,loadG:r.loadG,indicationG:r.indicationG,additionalLoadG:r.additionalLoadG,changeoverConfirmed:false,observedAt:at,unloadedIndicationG:r.unloadedIndicationG,zeroResetPerformed:r.zeroResetPerformed}))}))};
}
export async function loadFictionalDemoReadings(evaluationId:string,expectedVersion:number):Promise<ActionResult<{loaded:number;evaluationVersion:number}>>{
  const workspace=await getEvaluationWorkspace(evaluationId);if(!workspace.ok)return workspace;
  if(workspace.data.items.some(i=>i.session))return{ok:false,error:{code:"EXISTING_READINGS",message:"Demo readings were not loaded because at least one current attempt already exists."}};
  const db=await createSupabaseServerClient();if(!db)return{ok:false,error:{code:"CONFIGURATION_ERROR",message:"Authentication is not configured."}};
  const{data:spec}=await db.from("specification_revisions").select("id,version_no,accuracy_class,max_g::text,min_g::text,e_g::text,d_g::text,features").eq("id",workspace.data.specificationId).single();
  if(!spec)return{ok:false,error:{code:"SPECIFICATION_REQUIRED",message:"The saved specification could not be verified."}};const s=normalizeSpecification(spec).specifications;
  const matches=s.accuracyClass==="III"&&s.maxG===fixture.instrument.maxG&&s.minG===fixture.instrument.minG&&s.eG===fixture.instrument.eG&&s.dG===fixture.instrument.dG&&s.rangeType===fixture.instrument.rangeType&&s.receptor===fixture.instrument.receptor&&s.supportPoints===fixture.instrument.supportPoints&&s.maximumAdditiveTareG===fixture.instrument.maximumAdditiveTareG;
  if(!matches)return{ok:false,error:{code:"DEMO_SPEC_MISMATCH",message:"The fictional DEMO-30 readings require the matching saved DEMO-30 specification."}};
  let version=expectedVersion;let loaded=0;for(const item of workspace.data.items){const observations=raw(item.code);const saved=await saveObservationsService({evaluationId,planItemId:item.id,expectedEvaluationVersion:version,expectedSessionVersion:0,observations,conditions:{startTemperatureC:null,endTemperatureC:null,startedAt:now(),endedAt:now(),temperatureStabilityConfirmed:false},equipment:[{name:"Fictional demo mass set",type:"Mass standards",referenceNumber:"DEMO-NOT-PHYSICAL",suitabilityConfirmed:false,note:"Fixture data only; actual equipment not verified."}],procedureConfirmations:Object.fromEntries((item.code==="WEIGHING_INITIAL"?["PROGRESSIVE_LOADING_AND_UNLOADING","CHANGEOVER_OBSERVED","ZERO_DEVICE_STATE_RECORDED","ZERO_OUTSIDE_AUTOMATIC_RANGE_IF_OPERATING"]:item.code==="ECCENTRICITY_WEIGHTS"?["QUARTER_SEGMENTS_LOADED_IN_TURN","LOAD_DISTRIBUTION_RECORDED","ZERO_DEVICES_NOT_OPERATING","SKETCH_AND_DISPLAY_LOCATION_RECORDED"]:["UNLOADED_INSTRUMENT_AT_REST","RESET_IF_ZERO_DEVIATES","ZERO_DEVICES_OPERATING_IF_PRESENT"]).map(k=>[k,false])),remarks:"Fictional DEMO-30 raw readings loaded. No physical test or manual check is claimed."});
    if(!saved.ok)return saved;version=saved.data.evaluationVersion;const evaluated=await evaluateTestService({evaluationId,sessionId:saved.data.sessionId,expectedEvaluationVersion:version,expectedSessionVersion:saved.data.sessionVersion});if(!evaluated.ok)return evaluated;loaded++;}
  return{ok:true,data:{loaded,evaluationVersion:version},version};
}
