import "server-only";
import type { ActionResult } from "@/contracts/domain";
import type { AuditEventDto, ReportListRow, ReviewDetail, ReviewQueueRow } from "@/contracts/reports";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { requireActor, requireRole } from "@/server/auth/authorize";
const fail=<T>(message:string):ActionResult<T>=>({ok:false,error:{code:"READ_FAILED",message}});
export async function listApprovalQueue():Promise<ActionResult<ReviewQueueRow[]>>{try{requireRole(await requireActor(),"APPROVER");const db=await createSupabaseServerClient();if(!db)throw 0;const{data:evals,error}=await db.from("evaluations").select("id,instrument_id,application_number,current_submission_id").eq("state","UNDER_REVIEW").order("updated_at",{ascending:true});if(error)throw error;const rows:ReviewQueueRow[]=[];for(const e of evals??[]){const[{data:i},{data:v}]=await Promise.all([db.from("instruments").select("sample_identifier,model_id").eq("id",e.instrument_id).single(),db.from("report_versions").select("id,version_no,snapshot_sha256,created_at").eq("id",e.current_submission_id).single()]);if(!i||!v)continue;const{data:m}=await db.from("instrument_models").select("designation").eq("id",i.model_id).single();if(m)rows.push({evaluationId:e.id,instrumentId:e.instrument_id,applicationNumber:e.application_number,designation:m.designation,sampleIdentifier:i.sample_identifier,submittedAt:v.created_at,submissionId:v.id,versionNo:v.version_no,snapshotSha256:v.snapshot_sha256});}return{ok:true,data:rows,version:0};}catch{return fail("The authorized approval queue could not be loaded.");}}
export async function getReviewDetail(evaluationId:string):Promise<ActionResult<ReviewDetail>>{const q=await listApprovalQueue();if(!q.ok)return q;const row=q.data.find(x=>x.evaluationId===evaluationId);if(!row)return fail("This submission is not awaiting your laboratory review.");const db=await createSupabaseServerClient();if(!db)return fail("Authentication is not configured.");const[{data:e},{data:v}]=await Promise.all([db.from("evaluations").select("state,row_version::text").eq("id",evaluationId).single(),db.from("report_versions").select("snapshot").eq("id",row.submissionId).single()]);if(!e||!v)return fail("The submitted snapshot is unavailable.");return{ok:true,version:Number(e.row_version),data:{...row,evaluationVersion:Number(e.row_version),state:e.state,snapshot:v.snapshot}};}
export async function listReports():Promise<ActionResult<ReportListRow[]>>{try{await requireActor();const db=await createSupabaseServerClient();if(!db)throw 0;const{data:reports,error}=await db.from("reports").select("id,evaluation_id,report_number,created_at").order("created_at",{ascending:false});if(error)throw error;const rows:ReportListRow[]=[];for(const report of reports??[]){const[{data:e},{data:v}]=await Promise.all([db.from("evaluations").select("instrument_id,application_number,state").eq("id",report.evaluation_id).single(),db.from("report_versions").select("id,version_no").eq("report_id",report.id).eq("kind","FINAL").order("version_no",{ascending:false}).limit(1).maybeSingle()]);if(!e)continue;const{data:a}=v?await db.from("report_artifacts").select("id,state,sha256").eq("report_version_id",v.id).eq("format","PDF").maybeSingle():{data:null};rows.push({evaluationId:report.evaluation_id,instrumentId:e.instrument_id,applicationNumber:e.application_number,reportNumber:report.report_number,versionNo:v?.version_no??0,state:e.state,artifactId:a?.id??null,artifactState:a?.state??null,sha256:a?.sha256??null,createdAt:report.created_at});}return{ok:true,data:rows,version:0};}catch{return fail("The authorized report list could not be loaded.");}}
export async function listAuditTimeline(evaluationId:string):Promise<ActionResult<AuditEventDto[]>>{try{await requireActor();const db=await createSupabaseServerClient();if(!db)throw 0;const{data,error}=await db.from("audit_logs").select("id,action,entity_type,actor_id,created_at,metadata").eq("evaluation_id",evaluationId).order("created_at",{ascending:false}).limit(100);if(error)throw error;return{ok:true,data:(data??[]).map(r=>({id:String(r.id),action:r.action,entityType:r.entity_type,actorId:r.actor_id,createdAt:r.created_at,metadata:r.metadata??{}})),version:0};}catch{return fail("The audit timeline could not be loaded.");}}
