import "server-only";
import React from "react";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import type { ReportSnapshot } from "@/contracts/domain";
const s=StyleSheet.create({page:{padding:32,paddingBottom:46,fontFamily:"Helvetica",fontSize:9,color:"#16283d"},title:{fontSize:18,fontFamily:"Helvetica-Bold",marginBottom:6},sub:{fontSize:10,color:"#4b5563",marginBottom:14},h:{fontSize:12,fontFamily:"Helvetica-Bold",marginTop:12,marginBottom:5,borderBottom:"1 solid #cbd5e1",paddingBottom:3},row:{display:"flex",flexDirection:"row",borderBottom:"1 solid #e2e8f0",paddingVertical:3},key:{width:"34%",fontFamily:"Helvetica-Bold"},value:{width:"66%"},warning:{padding:8,backgroundColor:"#fff7ed",border:"1 solid #fdba74",marginVertical:8},small:{fontSize:7,color:"#475569"},pass:{color:"#166534",fontFamily:"Helvetica-Bold"},fail:{color:"#991b1b",fontFamily:"Helvetica-Bold"},footer:{position:"absolute",bottom:20,left:32,right:32,textAlign:"center",fontSize:7,color:"#64748b"}});
const KV=({k,v}:{k:string;v:React.ReactNode})=><View style={s.row}><Text style={s.key}>{k}</Text><Text style={s.value}>{v}</Text></View>;
const Footer=()=> <Text fixed style={s.footer} render={({pageNumber,totalPages})=>`SIH26035 selected-tests demonstration · page ${pageNumber}/${totalPages}`}/>;
function ReportDocument({snapshot}:{snapshot:ReportSnapshot}){return <Document title={`${snapshot.reportNumber} selected test report`} author="NAWI Lab SIH26035 prototype">
  <Page size="A4" style={s.page}><Text style={s.title}>Type Evaluation Test Report</Text><Text style={s.sub}>Selected Tests — Demonstration Only</Text><View style={s.warning}><Text>{snapshot.scopeStatement}</Text><Text>Full type conformity: NOT DETERMINED. This is not a Model Approval Certificate.</Text></View>
    <Text style={s.h}>Report identity</Text><KV k="Report / version" v={`${snapshot.reportNumber} / v${snapshot.versionNo}`}/><KV k="Application" v={snapshot.applicationNumber}/><KV k="Snapshot generated" v={snapshot.generatedAt}/><KV k="Laboratory" v={`${snapshot.laboratory.name}, ${snapshot.laboratory.address}`}/>
    <Text style={s.h}>Instrument and parties</Text><KV k="Designation" v={snapshot.instrument.designation}/><KV k="Sample / serial" v={`${snapshot.instrument.sampleIdentifier} / ${snapshot.instrument.serialNumber??"NOT RECORDED"}`}/><KV k="Manufacturer" v={`${snapshot.manufacturer.name}, ${snapshot.manufacturer.address}`}/><KV k="Applicant" v={`${snapshot.applicant.name}, ${snapshot.applicant.address}`}/>
    <Text style={s.h}>Declared specifications</Text><KV k="Class / range" v={`${snapshot.specifications.accuracyClass} / ${snapshot.specifications.rangeType}`}/><KV k="Min / Max" v={`${snapshot.specifications.minG} g / ${snapshot.specifications.maxG} g`}/><KV k="e / d" v={`${snapshot.specifications.eG} g / ${snapshot.specifications.dG} g`}/><KV k="Temperature" v={`${snapshot.specifications.declaredTemperatureMinC} °C to ${snapshot.specifications.declaredTemperatureMaxC} °C`}/>
    <Text style={s.h}>Selected-test summary</Text>{snapshot.testData.map((test,index)=><View key={index} wrap={false}><KV k={test.observations.type} v={<Text style={test.evaluation.outcome==="PASS"?s.pass:s.fail}>{test.evaluation.outcome}</Text>}/><Text style={s.small}>Engine {test.evaluation.engineVersion}; input SHA-256 {test.evaluation.inputSha256}</Text></View>)}<Footer/>
  </Page>
  {snapshot.testData.map((test,index)=><Page key={index} size="A4" style={s.page}><Text style={s.title}>{test.observations.type.replaceAll("_"," ")}</Text><Text style={s.sub}>Frozen observations and source-grounded calculations</Text>{test.evaluation.rules.map((r,i)=><View key={i} wrap={false} style={{marginBottom:8}}><Text style={s.h}>{r.testName}: {r.result}</Text><Text>Inputs: {JSON.stringify(r.inputValues)}</Text><Text>Calculated: {JSON.stringify(r.calculatedValues)}</Text><Text>Limits: {JSON.stringify(r.permissibleLimits)}</Text><Text>{r.calculation}</Text><Text>{r.reason}</Text><Text style={s.small}>Sources: {r.references.map(ref=>`${ref.standard} ${ref.edition}, ${ref.clause}, printed/PDF p${ref.printedPages.join(",")}/${ref.pdfPages.join(",")}`).join("; ")}</Text></View>)}<Text style={s.h}>Frozen raw observations</Text><Text style={s.small}>{JSON.stringify(test.observations)}</Text><Footer/></Page>)}
  <Page size="A4" style={s.page}><Text style={s.title}>Coverage, evidence and review</Text><Text style={s.h}>Conditions and equipment</Text><Text style={s.small}>{snapshot.conditions.length?JSON.stringify(snapshot.conditions):"No conditions recorded."}</Text><Text style={s.small}>{snapshot.testEquipment.length?JSON.stringify(snapshot.testEquipment):"No equipment recorded."}</Text><Text style={s.h}>Manual intake findings</Text><Text style={s.small}>{snapshot.manualIntake&&Object.keys(snapshot.manualIntake).length?JSON.stringify(snapshot.manualIntake):"No manual intake findings recorded."}</Text><Text style={s.h}>Coverage catalogue</Text>{snapshot.coverage.map(c=><View key={c.code} wrap={false} style={{marginBottom:4}}><Text>{c.code} — {c.status}</Text><Text style={s.small}>{c.explanation}</Text><Text style={s.small}>{c.references.map(ref=>`${ref.standard} ${ref.edition}, ${ref.clause}, p${ref.printedPages.join(",")}`).join("; ")}</Text></View>)}<Text style={s.h}>Recorded evidence</Text>{snapshot.evidence.length?snapshot.evidence.map(e=><Text key={e.attachmentId}>{e.description} — SHA-256 {e.sha256}</Text>):<Text>NOT RECORDED</Text>}<Text style={s.h}>Application approval for report issue</Text>{snapshot.approval?<><KV k="Approver" v={snapshot.approval.displayName}/><KV k="Decision time" v={snapshot.approval.decidedAt}/><KV k="Approved submission" v={`${snapshot.approval.submissionVersionId} / ${snapshot.approval.submissionSha256}`}/><KV k="Comment" v={snapshot.approval.comment??"No comment"}/></>:<Text>NOT APPROVED</Text>}<View style={s.warning}><Text>Approval is an application workflow decision. No legal digital signature or government acceptance is claimed.</Text></View><Footer/></Page>
  </Document>}
export async function renderReportPdf(snapshot:ReportSnapshot):Promise<Buffer>{return renderToBuffer(<ReportDocument snapshot={snapshot}/>);}
