import "server-only";
import type { ActionResult, ReportSnapshot } from "@/contracts/domain";
import type { IssuanceResult, ReviewDecision, ReviewResult, SubmissionResult } from "@/contracts/reports";
import { createHash } from "node:crypto";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { requireActor, requireAssignedTester, requireRole } from "@/server/auth/authorize";
import { createPrivilegedSupabaseClient, invokeCommand } from "@/server/db/commands";
import { buildSubmissionSnapshot } from "./snapshot";
import { renderReportPdf } from "./render";
const fail=<T>(code:string,message:string):ActionResult<T>=>({ok:false,error:{code,message}});
async function verifiedActor(){const db=await createSupabaseServerClient();if(!db)throw new Error("CONFIGURATION_ERROR");const{data,error}=await db.auth.getUser();if(error||!data.user)throw new Error("AUTH_REQUIRED");const actor=await requireActor();if(actor.id!==data.user.id)throw new Error("AUTH_CHANGED");return actor;}
export async function submitEvaluation(input:{evaluationId:string;expectedEvaluationVersion:number}):Promise<ActionResult<SubmissionResult>>{try{const actor=await requireAssignedTester(await verifiedActor(),input.evaluationId);const snapshot=await buildSubmissionSnapshot(input.evaluationId);return invokeCommand(actor,"command_submit",{p_evaluation_id:input.evaluationId,p_expected_evaluation_version:input.expectedEvaluationVersion,p_snapshot:snapshot});}catch{return fail("SUBMISSION_FAILED","The frozen selected-test snapshot could not be submitted.");}}
export async function reviewSubmission(input:{evaluationId:string;expectedEvaluationVersion:number;submissionId:string;submissionSha256:string;decision:ReviewDecision;comment?:string}):Promise<ActionResult<ReviewResult>>{try{const actor=requireRole(await verifiedActor(),"APPROVER");return invokeCommand(actor,"command_review",{p_evaluation_id:input.evaluationId,p_expected_evaluation_version:input.expectedEvaluationVersion,p_submission_id:input.submissionId,p_submission_sha256:input.submissionSha256,p_decision:input.decision,p_comment:input.comment??null});}catch{return fail("PERMISSION_DENIED","Only an active laboratory approver may review this exact submission.");}}
type Prepared={reportVersionId:string;artifactId:string;storagePath:string;snapshot:ReportSnapshot;snapshotSha256:string;artifactState:"PENDING"|"READY"|"FAILED";evaluationVersion:number};
export async function issueApprovedReport(evaluationId:string,expectedEvaluationVersion:number):Promise<ActionResult<IssuanceResult>>{let actor;let prepared:ActionResult<Prepared>|undefined;try{actor=requireRole(await verifiedActor(),"APPROVER");prepared=await invokeCommand(actor,"command_prepare_final",{p_evaluation_id:evaluationId,p_expected_evaluation_version:expectedEvaluationVersion});if(!prepared.ok)return prepared;const bytes=await renderReportPdf(prepared.data.snapshot);const sha256=createHash("sha256").update(bytes).digest("hex");const storage=createPrivilegedSupabaseClient().storage.from("nawi-reports");const upload=await storage.upload(prepared.data.storagePath,bytes,{contentType:"application/pdf",upsert:false});if(upload.error){const existing=await storage.download(prepared.data.storagePath);if(existing.error)throw new Error("PDF_UPLOAD_FAILED");const existingBytes=Buffer.from(await existing.data.arrayBuffer());if(createHash("sha256").update(existingBytes).digest("hex")!==sha256)throw new Error("PDF_PATH_CONFLICT");}
    return invokeCommand(actor,"command_finish_artifact",{p_evaluation_id:evaluationId,p_expected_evaluation_version:prepared.data.evaluationVersion,p_artifact_id:prepared.data.artifactId,p_sha256:sha256,p_byte_length:bytes.length});
  }catch(error){if(actor&&prepared?.ok)await invokeCommand(actor,"command_fail_artifact",{p_evaluation_id:evaluationId,p_artifact_id:prepared.data.artifactId,p_error_code:error instanceof Error?error.message:"PDF_GENERATION_FAILED"});return fail("PDF_FAILED","PDF generation or private storage failed. The approval remains retryable.");}}
